import { useState } from 'react';
import { Text, View } from 'react-native';
import { Grade, IntervalUnit, gradeLabel } from '../../domain/contacts';
import { Button, Card, Field, s } from '../../ui/components';
import { colors as c } from '../../ui/theme';

export function GradesScreen({ grades, saving, onAdd, onUpdate, onDelete }: { grades: Grade[]; saving: boolean; onUpdate: (code: string, amount: number, unit: IntervalUnit) => Promise<void>; onDelete: (code: string) => Promise<void>; onAdd: (code: string, amount: number, unit: IntervalUnit) => Promise<void> }) {
  const [editing, setEditing] = useState<string | null>(null);
  const [deleting, setDeleting] = useState<string | null>(null);
  const [code, setCode] = useState(''); const [amount, setAmount] = useState(''); const [unit, setUnit] = useState<IntervalUnit>('day'); const [error, setError] = useState('');
  const add = async () => { try { if (editing) await onUpdate(editing, Number(amount), unit); else await onAdd(code, Number(amount), unit); setEditing(null); setCode(''); setAmount(''); setError(''); } catch (e) { setError(e instanceof Error ? e.message : '新增失敗'); } };
  return <View style={{ gap: 20 }}><Card><Text style={s.title}>客戶分級與聯絡頻率</Text><Text style={s.muted}>A、B、C 是固定等級，可新增自訂名稱（1–20 字元），例如 VIP、AA、重點客戶。</Text>{grades.map(g => <View key={g.code} style={[s.row, { borderTopWidth: 1, borderColor: c.line, paddingTop: 16 }]}><Text style={{ fontSize: 22, color: c.green, fontWeight: '700', flex: 1, minWidth: 80, flexShrink: 1 }}>{g.code}</Text><Text style={[s.label, { flex: 1 }]}>{gradeLabel(g)}</Text><Text style={s.muted}>{g.fixed ? '固定，不可修改' : '自訂等級'}</Text>{!g.fixed && <><Button secondary disabled={saving} onPress={() => { setEditing(g.code); setCode(g.code); setAmount(String(g.amount)); setUnit(g.unit); }}>修改</Button><Button secondary disabled={saving} onPress={() => setDeleting(g.code)}>刪除</Button></>}</View>)}</Card><Card><Text style={s.title}>{editing ? `修改 ${editing} 的聯絡間隔` : '新增自訂等級'}</Text>{deleting && <View style={s.row}><Text style={s.muted}>確定刪除 {deleting}？</Text><Button disabled={saving} onPress={() => void onDelete(deleting).then(() => { setDeleting(null); setEditing(null); setCode(''); setAmount(''); }).catch(e => setError(e.message))}>確認刪除等級</Button><Button secondary onPress={() => setDeleting(null)}>取消刪除</Button></View>}{!editing && <Field label="等級名稱" value={code} onChange={setCode} placeholder="例如 VIP、AA、重點客戶" />}<Field label="聯絡間隔" value={amount} onChange={setAmount} keyboardType="number-pad" placeholder="例如 2" /><View style={s.row}>{(['day', 'week', 'month'] as const).map(u => <Button key={u} secondary={unit !== u} onPress={() => setUnit(u)}>{{ day: '天', week: '週', month: '月' }[u]}</Button>)}</View>{!!error && <Text accessibilityRole="alert" style={s.error}>{error}</Text>}<Button disabled={saving} onPress={() => void add()}>{saving ? '儲存中…' : editing ? '儲存等級' : '新增等級'}</Button>{editing && <Button secondary onPress={() => {setEditing(null);setCode('');setAmount('');}}>取消修改</Button>}</Card></View>;
}
